# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c05a685506596371b4cb4f0448ae7c0dda377496d802e4c0aef40bd3db4774352337e87260b9f8284329e30c6952411e1efb338768456ad948617d57ecec3d8

test:
  secret_key_base: 4bade259704c551f17c0afc760d1d6d98d309657303a8df4bb09c38dbf22208fc9b3f0aaf84c87b39c8105a4a02d8ea679c80330dcf207976f7362b949765ee7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 523lk5h2lkjlj6nlk4n6lk4
